Fix background color for titlebar buttons on Windows
crashmoney/obsidian-typewriter pull request #41
Opened 2024-01-26 15:09 UTC by orellazri

This PR fixes the background color for titlebar buttons on Windows and addresses https://github.com/crashmoney/obsidian-typewriter/issues/37

It seems that this bug only affects the theme when running in dark mode.

Before:
![before](https://github.com/crashmoney/obsidian-typewriter/assets/32670283/2f81c3af-8c10-4add-84ed-6de1097e3b4f)

After (Dark):
![fixed_dark](https://github.com/crashmoney/obsidian-typewriter/assets/32670283/bbc16ed5-cb23-4d98-9b40-1e671bec7b8f)

After (Light):
![fixed_light](https://github.com/crashmoney/obsidian-typewriter/assets/32670283/ae75b16d-612f-4479-8478-401a2dea51d8)

2024-05-01 11:30 UTC, crashmoney requested changes
The CSS looks ready to merge!

Only issue is that the fix is in `theme.css` rather than `obsidian.css`. The latter is deprecated for Obsidian versions below 1.0.0, so any commits made here won't show in the theme itself :)

2024-05-01 11:31 UTC, crashmoney commented
Hey @orellazri, thanks so much for the fix! I must have missed the alert for this 😅  Very appreciated, considering that I don't use Windows myself.

I've left my comments on a review!

2024-05-01 14:00 UTC, orellazri commented
@crashmoney No worries! Thanks for looking into my PR. I moved my change into `theme.css`

2024-05-02 07:16 UTC, crashmoney commented
Looks great! Merging this in :)

2024-05-02 07:17 UTC, merged